version: '3.1'
services:
  backend:
    container_name: payment
    image: course/payment
    ports:
      - "8080:8080"
    environment:
      SPRING_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge