spring:
  datasource:
    hikari:
      jdbc-url: ${SPRING_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
      username: ${SPRING_JDBC_USERNAME:postgres}
      password: ${SPRING_JDBC_PASSWORD:postgres}
      schema: ${SPRING_JDBC_SCHEMA:t1_course}
      maximum-pool-size: 10

server:
  port: 8081