CREATE TABLE IF NOT EXISTS users
(
    id bigint generated by default as identity (maxvalue 100)
        constraint users_id_pk
            primary key,
    limits  bigint not null default 0,
    balance bigint not null default 0
);